### ISSUE TITLE
train.zip 好像文件损坏了把

### ISSUE THREAD

**Issue by JunnYu** [hejunqing/webMedQA#1]
train.zip 好像文件损坏了把，压缩文件只有1kb，请问能不能提供新的链接

**Comment by yuanyuansiyuan** [comment]
我也遇到同样的问题，作者可以更新下train文件么~

**Comment by JunnYu** [comment]
> 我也遇到同样的问题，作者可以更新下train文件么~

我下载好了，在这个仓库点击train.zip这个文件，然后右上角有直接下载的链接，直接下载的没问题

**Comment by yuanyuansiyuan** [comment]
根据您的方法下载好了，非常感谢！

**Comment by yuanyuansiyuan** [comment]
> 
> 
> > 我也遇到同样的问题，作者可以更新下train文件么~
> 
> 我下载好了，在这个仓库点击train.zip这个文件，然后右上角有直接下载的链接，直接下载的没问题

按照您的建议可以了，谢谢~
